import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!; const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const MES_URL = "https://edbcjxgpyeqdxztenuyb.supabase.co"; const MES_ANON = "sb_publishable_K1c3q_XncSyaAI5wGPfcAg_iHcA7AB5";
const BASE_LEAVE = 15; const MAX_LEAVE = 25; const FIRST_YEAR_MAX = 11; const db = createClient(SUPABASE_URL, SERVICE_KEY);
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-user-token, apikey, content-type", "Access-Control-Allow-Methods": "GET, POST, OPTIONS" };
function json(b: unknown, s = 200): Response { return new Response(JSON.stringify(b), { status: s, headers: { ...cors, "Content-Type": "application/json" } }); }
function nz(o: any) { if (o && typeof o === "object") { for (const k in o) if (o[k] === "") o[k] = null; } return o; }
function serviceMonths(h: Date, b: Date): number { let m = (b.getUTCFullYear()-h.getUTCFullYear())*12+(b.getUTCMonth()-h.getUTCMonth()); if (b.getUTCDate()<h.getUTCDate()) m--; return Math.max(m,0); }
function annualLeave(y: number): number { return Math.min(Math.floor((y-1)/2+BASE_LEAVE), MAX_LEAVE); }
function firstYearLeave(mo: number): number { return Math.min(mo, FIRST_YEAR_MAX); }
function accrued(h: Date, b: Date): number { const m=serviceMonths(h,b); return m<12?firstYearLeave(m):annualLeave(Math.floor(m/12)); }
function baseDateFor(e: any, y: number): Date { const h=new Date(e.hire_date+"T00:00:00Z"); return e.accrual_basis==="fiscal"?new Date(Date.UTC(y,0,1)):new Date(Date.UTC(y,h.getUTCMonth(),h.getUTCDate())); }
async function leaveStatus(e: any, y: number) { const eid=e.id; const sum=async(t:string,c:string):Promise<number>=>{const{data}=await db.from(t).select(c).eq("employee_id",eid).eq("applied_year",y);return(data||[]).reduce((s:number,r:any)=>s+Number(r[c]||0),0);}; const acc=accrued(new Date(e.hire_date+"T00:00:00Z"),baseDateFor(e,y)); const used=await sum("leave_records","used_days"); const added=await sum("leave_adjustments","add_days"); const ded=await sum("leave_adjustments","deduct_days"); const allw=await sum("leave_allowances","deduct_days"); const rem=acc+added-(used+ded+allw); const r6=(n:number)=>Math.round(n*1e6)/1e6; return {employee_id:eid,name:e.name,department:e.department,position:e.position,hire_date:e.hire_date,year:y,accrual_basis:e.accrual_basis,accrued_days:acc,used_days:r6(used),added_days:r6(added),deducted_days:r6(ded),allowance_days:r6(allw),remaining_days:r6(rem)}; }
async function myRecords(eid: number, y: number) { const { data } = await db.from("leave_records").select("*").eq("employee_id", eid).eq("applied_year", y).order("start_date"); const { data: lts } = await db.from("leave_types").select("code,label"); const lm = new Map((lts || []).map((t: any) => [t.code, t.label])); return (data || []).map((r: any) => ({ id: r.id, start_date: r.start_date, end_date: r.end_date, leave_type_code: r.leave_type_code, type_label: lm.get(r.leave_type_code) || r.leave_type_code, used_days: r.used_days, reason: r.reason, note: r.note })); }
async function attRows(y: number, mo: number, empId: number | null) { let q = db.from("attendance_days").select("*"); if (mo) { const mm = String(mo).padStart(2, "0"); const ed = new Date(Date.UTC(y, mo, 0)).getUTCDate(); q = q.gte("work_date", `${y}-${mm}-01`).lte("work_date", `${y}-${mm}-${String(ed).padStart(2, "0")}`); } else { q = q.gte("work_date", `${y}-01-01`).lte("work_date", `${y}-12-31`); } if (empId) q = q.eq("employee_id", empId); const { data } = await q.order("work_date"); const { data: emps } = await db.from("employees").select("id,name,department"); const nm = new Map((emps || []).map((e: any) => [e.id, e])); return (data || []).map((r: any) => ({ ...r, employee_name: r.employee_id ? (nm.get(r.employee_id)?.name || r.name_raw) : (r.name_raw || "미매칭"), department: r.employee_id ? (nm.get(r.employee_id)?.department || "") : "" })); }
async function computeUsedDays(code:string,s:string,e:string,ex:boolean):Promise<number>{ const{data:lt}=await db.from("leave_types").select("deduct_days,is_deductible").eq("code",code).maybeSingle(); if(lt&&lt.is_deductible===false)return 0; const d=Number(lt?.deduct_days??1); if(d<1)return d; const st=new Date(s+"T00:00:00Z"); const en=new Date(e+"T00:00:00Z"); let wd=0; const ds:string[]=[]; for(let x=new Date(st);x<=en;x.setUTCDate(x.getUTCDate()+1)){const w=x.getUTCDay();if(w!==0&&w!==6){wd++;ds.push(x.toISOString().slice(0,10));}} if(ex&&ds.length){const{data:hs}=await db.from("holidays").select("holiday_date").gte("holiday_date",s).lte("holiday_date",e); const hset=new Set((hs||[]).map((h:any)=>String(h.holiday_date).slice(0,10))); for(const x of ds)if(hset.has(x))wd--;} return Math.max(wd,0)*d; }
async function dashboard(y:number){ const{data:emps}=await db.from("employees").select("*").order("department").order("name"); const{data:recs}=await db.from("leave_records").select("employee_id,used_days").eq("applied_year",y); const{data:adjs}=await db.from("leave_adjustments").select("employee_id,add_days,deduct_days").eq("applied_year",y); const{data:alls}=await db.from("leave_allowances").select("employee_id,deduct_days").eq("applied_year",y); const sb=(rows:any[],c:string)=>{const m=new Map<number,number>();for(const r of(rows||[]))m.set(r.employee_id,(m.get(r.employee_id)||0)+Number(r[c]||0));return m;}; const uM=sb(recs||[],"used_days"),aM=sb(adjs||[],"add_days"),dM=sb(adjs||[],"deduct_days"),lM=sb(alls||[],"deduct_days"); const r6=(n:number)=>Math.round(n*1e6)/1e6; return(emps||[]).map((e:any)=>{const acc=accrued(new Date(e.hire_date+"T00:00:00Z"),baseDateFor(e,y));const used=uM.get(e.id)||0,added=aM.get(e.id)||0,ded=dM.get(e.id)||0,allw=lM.get(e.id)||0;const tot=acc+added-ded;const rem=tot-(used+allw);const rate=tot>0?used/tot:0;return{employee_id:e.id,name:e.name,department:e.department,position:e.position,status:e.status,accrued_days:acc,used_days:r6(used),remaining_days:r6(rem),usage_rate:r6(rate)};}); }
async function calendar(y:number,mo:number){ const mm=String(mo).padStart(2,"0"); const start=`${y}-${mm}-01`; const ed=new Date(Date.UTC(y,mo,0)).getUTCDate(); const end=`${y}-${mm}-${String(ed).padStart(2,"0")}`; const{data:recs}=await db.from("leave_records").select("*").lte("start_date",end).gte("end_date",start).order("start_date"); const{data:emps}=await db.from("employees").select("id,name,department"); const nm=new Map((emps||[]).map((e:any)=>[e.id,e])); const out=(recs||[]).map((r:any)=>({id:r.id,employee_id:r.employee_id,employee_name:nm.get(r.employee_id)?.name||"?",department:nm.get(r.employee_id)?.department||"",leave_type_code:r.leave_type_code,start_date:r.start_date,end_date:r.end_date,used_days:r.used_days})); const{data:hols}=await db.from("holidays").select("*").gte("holiday_date",start).lte("holiday_date",end); return{year:y,month:mo,records:out,holidays:hols||[]}; }
async function alerts(){ const today=new Date(); const now=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate())); const WINDOW=30;
  const dMonthDay=(s:string)=>{const d=new Date(s+"T00:00:00Z"); let nx=new Date(Date.UTC(now.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())); if(nx<now) nx=new Date(Date.UTC(now.getUTCFullYear()+1,d.getUTCMonth(),d.getUTCDate())); return Math.round((nx.getTime()-now.getTime())/86400000);};
  const dUntil=(s:string)=>{const d=new Date(s+"T00:00:00Z"); return Math.round((d.getTime()-now.getTime())/86400000);};
  const{data:emps}=await db.from("employees").select("id,name,department,birth_date,hire_date,contract_end").neq("status","퇴사");
  const{data:lic}=await db.from("employee_profile_items").select("employee_id,title,date_to,category").in("category",["license","training"]).not("date_to","is",null);
  const nm=new Map((emps||[]).map((e:any)=>[e.id,{name:e.name,department:e.department}]));
  const out:any[]=[];
  for(const e of (emps||[])){
    if(e.birth_date){const dd=dMonthDay(e.birth_date); if(dd>=0&&dd<=WINDOW) out.push({type:"생일",name:e.name,department:e.department,date:e.birth_date,days_left:dd,detail:""});}
    if(e.hire_date){const dd=dMonthDay(e.hire_date); if(dd>=0&&dd<=WINDOW){const yrs=now.getUTCFullYear()-Number(String(e.hire_date).slice(0,4)); out.push({type:"입사기념일",name:e.name,department:e.department,date:e.hire_date,days_left:dd,detail:yrs+"주년"});}}
    if(e.contract_end){const dd=dUntil(e.contract_end); if(dd>=-30&&dd<=WINDOW) out.push({type:"계약만료",name:e.name,department:e.department,date:e.contract_end,days_left:dd,detail:""});}
  }
  for(const l of (lic||[])){const dd=dUntil(l.date_to); if(dd>=-30&&dd<=WINDOW){const info=nm.get(l.employee_id)||{name:"?",department:""}; out.push({type:(l.category==="training"?"교육만료":"자격만료"),name:info.name,department:info.department,date:l.date_to,days_left:dd,detail:l.title||""});}}
  out.sort((a,b)=>a.days_left-b.days_left); return out;
}
async function trainingOverview(){ const{data:items}=await db.from("employee_profile_items").select("*").in("category",["training","license"]).order("date_to"); const{data:emps}=await db.from("employees").select("id,name,department,status"); const nm=new Map((emps||[]).map((e:any)=>[e.id,e])); return (items||[]).map((it:any)=>({...it, employee_name:nm.get(it.employee_id)?.name||"?", department:nm.get(it.employee_id)?.department||"", emp_status:nm.get(it.employee_id)?.status})); }
async function permsFor(role:string){ if(role==="master")return{master:true,set:{} as Record<string,boolean>}; const{data}=await db.from("role_permissions").select("perm_key,allowed").eq("role",role); const set:Record<string,boolean>={}; for(const r of(data||[]))set[r.perm_key]=!!r.allowed; return{master:false,set}; }
async function identify(req:Request){ const token=req.headers.get("x-user-token")||""; if(!token)return{role:"anon" as string}; const r=await fetch(`${MES_URL}/auth/v1/user`,{headers:{Authorization:`Bearer ${token}`,apikey:MES_ANON}}); if(!r.ok)return{role:"anon" as string}; const u=await r.json(); const email=(u.email||"").toLowerCase(); if(!email)return{role:"anon" as string}; const{data:adminRow}=await db.from("app_admins").select("email,role").eq("email",email).maybeSingle(); if(adminRow)return{role:adminRow.role as string,email}; const{data:emp}=await db.from("employees").select("*").eq("login_email",email).maybeSingle(); if(emp)return{role:"employee" as string,email,employee:emp}; return{role:"none" as string,email}; }
Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  const url = new URL(req.url); let path = url.pathname.replace(/^\/functions\/v1\/hr/, "").replace(/^\/hr/, ""); if (path === "") path = "/";
  const year = Number(url.searchParams.get("year")) || new Date().getUTCFullYear();
  try {
    if (path === "/") return json({ status: "ok" });
    const id: any = await identify(req);
    if (id.role === "anon") return json({ detail: "로그인이 필요합니다." }, 401);
    const perms = await permsFor(id.role); const ok = (k: string) => perms.master || !!perms.set[k]; const deny = () => json({ detail: "이 작업 권한이 없습니다." }, 403); const isMaster = id.role === "master";
    if (path === "/me") { const e = id.employee; return json({ email: id.email, role: id.role, is_master: isMaster, permissions: perms.master ? null : perms.set, employee_id: e?.id ?? null, name: e?.name ?? null }); }
    if (path === "/me/leave-status") { const e = id.employee; if (!e) return json({ detail: "본인과 연결된 사원 정보가 없습니다." }, 404); return json(await leaveStatus(e, year)); }
    if (path === "/me/leave-records") { const e = id.employee; if (!e) return json([]); return json(await myRecords(e.id, year)); }
    if (path === "/me/attendance") { const e = id.employee; if (!e) return json([]); return json(await attRows(year, Number(url.searchParams.get("month")) || 0, e.id)); }
    if (path === "/me/leave-requests" && req.method === "POST") { const e = id.employee; if (!e) return json({ detail: "본인과 연결된 사원 정보가 없습니다." }, 403); const b = nz(await req.json()); const s = String(b.start_date); const en = String(b.end_date || b.start_date); const ex = b.exclude_holiday !== false; const ay = b.applied_year || Number(s.slice(0, 4)); const { data, error } = await db.from("leave_requests").insert({ employee_id: e.id, applied_year: ay, leave_type_code: b.leave_type_code, start_date: s, end_date: en, exclude_holiday: ex, reason: b.reason || null, status: "pending" }).select().single(); if (error) return json({ detail: "신청 실패: " + error.message }, 400); return json(data); }
    if (path === "/me/leave-requests" && req.method === "GET") { const e = id.employee; if (!e) return json([]); const { data } = await db.from("leave_requests").select("*").eq("employee_id", e.id).eq("applied_year", year).order("created_at", { ascending: false }); const { data: lts } = await db.from("leave_types").select("code,label"); const lm = new Map((lts || []).map((t: any) => [t.code, t.label])); return json((data || []).map((r: any) => ({ ...r, type_label: lm.get(r.leave_type_code) || r.leave_type_code }))); }
    if (path === "/leave-types") { const { data } = await db.from("leave_types").select("*").order("deduct_days", { ascending: false }); return json(data); }
    if (path === "/menu" && req.method === "GET") { const { data: groups } = await db.from("menu_groups").select("*").order("sort_order"); const { data: tabs } = await db.from("menu_tabs").select("*").order("sort_order"); return json({ groups: groups || [], tabs: tabs || [] }); }
    const STAFF = ["master", "admin", "manager"]; if (!STAFF.includes(id.role)) return json({ detail: "권한이 없습니다." }, 403);
    if (path === "/alerts") return json(await alerts());
    if (path === "/training-overview") return json(await trainingOverview());
    if (path === "/leave-requests" && req.method === "GET") { if (!ok("tab:approvals")) return deny(); const st = url.searchParams.get("status"); let q = db.from("leave_requests").select("*").eq("applied_year", year); if (st) q = q.eq("status", st); const { data } = await q.order("created_at", { ascending: false }); const { data: emps } = await db.from("employees").select("id,name,department"); const nm = new Map((emps || []).map((e: any) => [e.id, e])); const { data: lts } = await db.from("leave_types").select("code,label"); const lm = new Map((lts || []).map((t: any) => [t.code, t.label])); return json((data || []).map((r: any) => ({ ...r, employee_name: nm.get(r.employee_id)?.name || "?", department: nm.get(r.employee_id)?.department || "", type_label: lm.get(r.leave_type_code) || r.leave_type_code }))); }
    const mqa = path.match(/^\/leave-requests\/(\d+)\/approve$/); if (mqa && req.method === "POST") { if (!ok("tab:approvals")) return deny(); const rid = Number(mqa[1]); const { data: rq } = await db.from("leave_requests").select("*").eq("id", rid).maybeSingle(); if (!rq) return json({ detail: "신청 없음" }, 404); if (rq.status !== "pending") return json({ detail: "이미 처리된 신청입니다." }, 400); const ex = rq.exclude_holiday !== false; const used = await computeUsedDays(rq.leave_type_code, String(rq.start_date), String(rq.end_date), ex); const { data: rec, error: e1 } = await db.from("leave_records").insert({ employee_id: rq.employee_id, applied_year: rq.applied_year, leave_type_code: rq.leave_type_code, start_date: rq.start_date, end_date: rq.end_date, exclude_holiday: ex, used_days: used, reason: rq.reason || null, note: "전자결재 승인" }).select().single(); if (e1) return json({ detail: "승인 실패(기록 생성): " + e1.message }, 400); const { error: e2 } = await db.from("leave_requests").update({ status: "approved", decided_by: id.email, decided_at: new Date().toISOString(), leave_record_id: rec.id }).eq("id", rid); if (e2) return json({ detail: "승인 실패(상태 갱신): " + e2.message }, 400); return json({ ok: true, used_days: used, leave_record_id: rec.id }); }
    const mqr = path.match(/^\/leave-requests\/(\d+)\/reject$/); if (mqr && req.method === "POST") { if (!ok("tab:approvals")) return deny(); const rid = Number(mqr[1]); const b = await req.json().catch(() => ({})); const { data: rq } = await db.from("leave_requests").select("status").eq("id", rid).maybeSingle(); if (!rq) return json({ detail: "신청 없음" }, 404); if (rq.status !== "pending") return json({ detail: "이미 처리된 신청입니다." }, 400); const { error } = await db.from("leave_requests").update({ status: "rejected", decided_by: id.email, decided_at: new Date().toISOString(), decision_note: b.note || null }).eq("id", rid); if (error) return json({ detail: "반려 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/attendance" && req.method === "GET") { if (!ok("tab:attendance")) return deny(); const mo = Number(url.searchParams.get("month")) || 0; const empParam = url.searchParams.get("employee_id"); return json(await attRows(year, mo, empParam ? Number(empParam) : null)); }
    if (path === "/attendance/import" && req.method === "POST") { if (!ok("tab:attendance")) return deny(); const b = await req.json(); const rows = b.rows || []; const { data: emps } = await db.from("employees").select("id,name,attendance_uid"); const byUid = new Map(); const byName = new Map(); for (const e of (emps || [])) { if (e.attendance_uid) byUid.set(String(e.attendance_uid), e.id); if (e.name) byName.set(e.name, e.id); } let matched = 0; const payload = rows.map((r: any) => { const uid = r.user_ext_id != null && r.user_ext_id !== "" ? String(r.user_ext_id) : null; const name = r.name || null; let eid: number | null = null; if (uid && byUid.has(uid)) eid = byUid.get(uid); else if (name && byName.has(name)) eid = byName.get(name); if (eid) matched++; const key = (uid || name || "?") + "|" + r.work_date; return { employee_id: eid, user_ext_id: uid, name_raw: name, work_date: r.work_date, day_name: r.day_name || null, clock_in: r.clock_in || null, clock_out: r.clock_out || null, basic_min: r.basic_min ?? null, overtime_min: r.overtime_min ?? null, total_min: r.total_min ?? null, recognized_min: r.recognized_min ?? null, source: "excel", dedup_key: key }; }); const { data, error } = await db.from("attendance_days").upsert(payload, { onConflict: "dedup_key" }).select("id"); if (error) return json({ detail: "근태 업로드 실패: " + error.message }, 400); return json({ inserted: (data || []).length, matched, total: rows.length }); }
    if (path === "/permissions" && req.method === "GET") { if (!isMaster) return deny(); const { data } = await db.from("role_permissions").select("*"); return json(data || []); }
    if (path === "/permissions/update" && req.method === "POST") { if (!isMaster) return deny(); const b = await req.json(); const { error } = await db.from("role_permissions").upsert({ role: b.role, perm_key: b.perm_key, allowed: !!b.allowed }, { onConflict: "role,perm_key" }); if (error) return json({ detail: "권한 저장 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/admins" && req.method === "GET") { if (!isMaster) return deny(); const { data } = await db.from("app_admins").select("email,role,note").order("role"); return json(data || []); }
    if (path === "/admins/upsert" && req.method === "POST") { if (!isMaster) return deny(); const b = await req.json(); const em = String(b.email || "").trim().toLowerCase(); if (!em) return json({ detail: "이메일 필요" }, 400); const role = ["admin", "manager", "master"].includes(b.role) ? b.role : "admin"; const { error } = await db.from("app_admins").upsert({ email: em, role, note: b.note || null }, { onConflict: "email" }); if (error) return json({ detail: "저장 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/admins/delete" && req.method === "POST") { if (!isMaster) return deny(); const b = await req.json(); const em = String(b.email || "").trim().toLowerCase(); const { data: tgt } = await db.from("app_admins").select("role").eq("email", em).maybeSingle(); if (tgt && tgt.role === "master") return json({ detail: "master 계정은 삭제할 수 없습니다." }, 400); const { error } = await db.from("app_admins").delete().eq("email", em); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/menu/group/upsert" && req.method === "POST") { if (!isMaster) return deny(); const b = await req.json(); if (b.id) { const { error } = await db.from("menu_groups").update({ name: b.name, sort_order: Number(b.sort_order) || 0 }).eq("id", b.id); if (error) return json({ detail: "저장 실패: " + error.message }, 400); } else { const { error } = await db.from("menu_groups").insert({ name: b.name, sort_order: Number(b.sort_order) || 0 }); if (error) return json({ detail: "저장 실패: " + error.message }, 400); } return json({ ok: true }); }
    if (path === "/menu/group/delete" && req.method === "POST") { if (!isMaster) return deny(); const b = await req.json(); const { error } = await db.from("menu_groups").delete().eq("id", b.id); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/menu/tab/update" && req.method === "POST") { if (!isMaster) return deny(); const b = await req.json(); const upd: any = {}; if (b.group_id !== undefined) upd.group_id = b.group_id || null; if (b.label !== undefined) upd.label = b.label; if (b.sort_order !== undefined) upd.sort_order = Number(b.sort_order) || 0; const { error } = await db.from("menu_tabs").update(upd).eq("tab_key", b.tab_key); if (error) return json({ detail: "저장 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/dashboard") return json(await dashboard(year));
    if (path === "/calendar") { const mo = Number(url.searchParams.get("month")) || (new Date().getUTCMonth() + 1); return json(await calendar(year, mo)); }
    if (path === "/holidays" && req.method === "GET") { const { data } = await db.from("holidays").select("*").eq("year", year).order("holiday_date"); return json(data); }
    if (path === "/employees" && req.method === "GET") { const { data } = await db.from("employees").select("*").order("id"); return json(data); }
    const mdet = path.match(/^\/employees\/(\d+)\/detail$/); if (mdet) { const eid = Number(mdet[1]); const { data: emp } = await db.from("employees").select("*").eq("id", eid).maybeSingle(); if (!emp) return json({ detail: "사원 없음" }, 404); const { data: items } = await db.from("employee_profile_items").select("*").eq("employee_id", eid).order("category").order("date_from"); return json({ employee: emp, items: items || [] }); }
    const mr = path.match(/^\/employees\/(\d+)\/leave-records$/); if (mr) { const { data } = await db.from("leave_records").select("*").eq("employee_id", Number(mr[1])).eq("applied_year", year).order("start_date"); return json(data); }
    const maj = path.match(/^\/employees\/(\d+)\/adjustments$/); if (maj) { const { data } = await db.from("leave_adjustments").select("*").eq("employee_id", Number(maj[1])).eq("applied_year", year).order("id"); return json(data); }
    const mal = path.match(/^\/employees\/(\d+)\/allowances$/); if (mal) { const { data } = await db.from("leave_allowances").select("*").eq("employee_id", Number(mal[1])).eq("applied_year", year).order("id"); return json(data); }
    const msx = path.match(/^\/employees\/(\d+)\/leave-status$/); if (msx) { const { data: e } = await db.from("employees").select("*").eq("id", Number(msx[1])).maybeSingle(); if (!e) return json({ detail: "사원 없음" }, 404); return json(await leaveStatus(e, year)); }
    const matt = path.match(/^\/employees\/(\d+)\/attendance$/); if (matt) { return json(await attRows(year, Number(url.searchParams.get("month")) || 0, Number(matt[1]))); }
    if (path === "/employees/bulk" && req.method === "POST") { if (!ok("tab:employees")) return deny(); const b = await req.json(); const list = (b.employees || []).map((e: any) => { nz(e); return { ...e, login_email: e.login_email ? String(e.login_email).trim().toLowerCase() : null }; }); const { data, error } = await db.from("employees").insert(list).select(); if (error) return json({ detail: "일괄 등록 실패: " + error.message }, 400); return json({ inserted: (data || []).length }); }
    if (path === "/employees" && req.method === "POST") { if (!ok("tab:employees")) return deny(); const b = nz(await req.json()); b.login_email = b.login_email ? String(b.login_email).trim().toLowerCase() : null; const { data, error } = await db.from("employees").insert(b).select().single(); if (error) return json({ detail: "사원 등록 실패: " + error.message }, 400); return json(data); }
    const mu = path.match(/^\/employees\/(\d+)\/update$/); if (mu && req.method === "POST") { if (!ok("tab:employees")) return deny(); const b = nz(await req.json()); if (b.login_email !== undefined) b.login_email = b.login_email ? String(b.login_email).trim().toLowerCase() : null; delete b.id; delete b.created_at; const { data, error } = await db.from("employees").update(b).eq("id", Number(mu[1])).select().single(); if (error) return json({ detail: "수정 실패: " + error.message }, 400); return json(data); }
    const md = path.match(/^\/employees\/(\d+)\/delete$/); if (md && req.method === "POST") { if (!ok("tab:employees")) return deny(); const { error } = await db.from("employees").delete().eq("id", Number(md[1])); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    const mpi = path.match(/^\/employees\/(\d+)\/profile-items$/); if (mpi && req.method === "POST") { if (!(ok("tab:profile") || ok("tab:training"))) return deny(); const b = nz(await req.json()); const row = { employee_id: Number(mpi[1]), category: b.category, title: b.title || null, detail: b.detail || null, date_from: b.date_from || null, date_to: b.date_to || null, note: b.note || null }; const { data, error } = await db.from("employee_profile_items").insert(row).select().single(); if (error) return json({ detail: "저장 실패: " + error.message }, 400); return json(data); }
    const mpid = path.match(/^\/profile-items\/(\d+)\/delete$/); if (mpid && req.method === "POST") { if (!(ok("tab:profile") || ok("tab:training"))) return deny(); const { error } = await db.from("employee_profile_items").delete().eq("id", Number(mpid[1])); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/leave-records" && req.method === "POST") { if (!ok("tab:records")) return deny(); const b = nz(await req.json()); const s = String(b.start_date); const e = String(b.end_date || b.start_date); const ex = b.exclude_holiday !== false; let used = b.used_days; if (used === undefined || used === null || used === "") used = await computeUsedDays(b.leave_type_code, s, e, ex); const ay = b.applied_year || Number(s.slice(0, 4)); const { data, error } = await db.from("leave_records").insert({ employee_id: b.employee_id, applied_year: ay, leave_type_code: b.leave_type_code, start_date: s, end_date: e, exclude_holiday: ex, used_days: used, reason: b.reason || null, note: b.note || null }).select().single(); if (error) return json({ detail: "저장 실패: " + error.message }, 400); return json(data); }
    const mrd = path.match(/^\/leave-records\/(\d+)\/delete$/); if (mrd && req.method === "POST") { if (!ok("tab:records")) return deny(); const { error } = await db.from("leave_records").delete().eq("id", Number(mrd[1])); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/leave-adjustments" && req.method === "POST") { if (!ok("tab:adjust")) return deny(); const b = nz(await req.json()); const { data, error } = await db.from("leave_adjustments").insert({ employee_id: b.employee_id, applied_year: b.applied_year || new Date().getUTCFullYear(), add_days: Number(b.add_days) || 0, deduct_days: Number(b.deduct_days) || 0, reason: b.reason || null }).select().single(); if (error) return json({ detail: "저장 실패: " + error.message }, 400); return json(data); }
    const majd = path.match(/^\/leave-adjustments\/(\d+)\/delete$/); if (majd && req.method === "POST") { if (!ok("tab:adjust")) return deny(); const { error } = await db.from("leave_adjustments").delete().eq("id", Number(majd[1])); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/leave-allowances" && req.method === "POST") { if (!ok("tab:adjust")) return deny(); const b = nz(await req.json()); const { data, error } = await db.from("leave_allowances").insert({ employee_id: b.employee_id, applied_year: b.applied_year || new Date().getUTCFullYear(), hourly_wage: b.hourly_wage != null && b.hourly_wage !== "" ? Number(b.hourly_wage) : null, deduct_days: Number(b.deduct_days) || 0, paid_amount: b.paid_amount != null && b.paid_amount !== "" ? Number(b.paid_amount) : null, paid_date: b.paid_date || null, note: b.note || null }).select().single(); if (error) return json({ detail: "저장 실패: " + error.message }, 400); return json(data); }
    const mald = path.match(/^\/leave-allowances\/(\d+)\/delete$/); if (mald && req.method === "POST") { if (!ok("tab:adjust")) return deny(); const { error } = await db.from("leave_allowances").delete().eq("id", Number(mald[1])); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    if (path === "/leave-types/update" && req.method === "POST") { if (!ok("tab:settings")) return deny(); const b = await req.json(); const upd: any = {}; if (b.deduct_days !== undefined) upd.deduct_days = Number(b.deduct_days); if (b.is_deductible !== undefined) upd.is_deductible = !!b.is_deductible; if (b.label !== undefined) upd.label = b.label; const { data, error } = await db.from("leave_types").update(upd).eq("code", b.code).select().single(); if (error) return json({ detail: "수정 실패: " + error.message }, 400); return json(data); }
    if (path === "/holidays" && req.method === "POST") { if (!ok("tab:settings")) return deny(); const b = await req.json(); const { data, error } = await db.from("holidays").insert({ holiday_date: b.holiday_date, name: b.name }).select().single(); if (error) return json({ detail: "추가 실패: " + error.message }, 400); return json(data); }
    if (path === "/holidays/import" && req.method === "POST") { if (!ok("tab:settings")) return deny(); const r = await fetch(`https://date.nager.at/api/v3/PublicHolidays/${year}/KR`); if (!r.ok) return json({ detail: "공휴일 API 실패" }, 502); const list = await r.json(); let ins = 0; for (const h of (list || [])) { const { error } = await db.from("holidays").insert({ holiday_date: h.date, name: h.localName || h.name }); if (!error) ins++; } return json({ inserted: ins, total: (list || []).length }); }
    const mhd = path.match(/^\/holidays\/(\d+)\/delete$/); if (mhd && req.method === "POST") { if (!ok("tab:settings")) return deny(); const { error } = await db.from("holidays").delete().eq("id", Number(mhd[1])); if (error) return json({ detail: "삭제 실패: " + error.message }, 400); return json({ ok: true }); }
    return json({ detail: "알 수 없는 경로: " + path }, 404);
  } catch (e) { return json({ detail: "서버 오류: " + String(e) }, 500); }
});
